USE [master]
GO
/****** Object:  Database [NLS]    Script Date: 10/18/2025 3:30:31 PM ******/
CREATE DATABASE [NLS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NLS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NLS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NLS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NLS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [NLS] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NLS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NLS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NLS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NLS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NLS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NLS] SET ARITHABORT OFF 
GO
ALTER DATABASE [NLS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [NLS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NLS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NLS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NLS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NLS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NLS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NLS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NLS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NLS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [NLS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NLS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NLS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NLS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NLS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NLS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NLS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NLS] SET RECOVERY FULL 
GO
ALTER DATABASE [NLS] SET  MULTI_USER 
GO
ALTER DATABASE [NLS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NLS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NLS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NLS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NLS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NLS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'NLS', N'ON'
GO
ALTER DATABASE [NLS] SET QUERY_STORE = ON
GO
ALTER DATABASE [NLS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [NLS]
GO
/****** Object:  Table [dbo].[Colors]    Script Date: 10/18/2025 3:30:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Colors](
	[id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[value] [bigint] NOT NULL,
 CONSTRAINT [PK_Colors] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Colors_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Colors_name] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[File_Aliases]    Script Date: 10/18/2025 3:30:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[File_Aliases](
	[id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[alias] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_File_Aliases] PRIMARY KEY CLUSTERED 
(
	[alias] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_File_Aliases_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_File_Aliases_name] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Files]    Script Date: 10/18/2025 3:30:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Files](
	[id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[description] [nvarchar](max) NOT NULL,
	[used_by] [nvarchar](max) NOT NULL,
	[icon] [binary](50) NOT NULL,
	[icon_class_name] [nvarchar](50) NOT NULL,
	[Icon_UTF_16_codes] [bigint] NOT NULL,
	[Icon_Hex_Code] [bigint] NOT NULL,
 CONSTRAINT [PK_Files] PRIMARY KEY CLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Files_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Files_name] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Folder_Aliases]    Script Date: 10/18/2025 3:30:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Folder_Aliases](
	[id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[alias] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Folder_Aliases] PRIMARY KEY CLUSTERED 
(
	[alias] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Folder_Aliases_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Folder_Aliases_name] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Folders]    Script Date: 10/18/2025 3:30:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Folders](
	[id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
	[description] [nvarchar](max) NULL,
	[used_by] [nvarchar](max) NULL,
	[icon] [binary](50) NOT NULL,
	[icon_class_name] [nvarchar](50) NULL,
	[Icon_UTF_16_codes] [bigint] NULL,
	[Icon_Hex_Code] [bigint] NULL,
 CONSTRAINT [PK_Folders] PRIMARY KEY CLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Folders_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Folders_name] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Theme_colors]    Script Date: 10/18/2025 3:30:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Theme_colors](
	[id] [int] NOT NULL,
	[element] [nvarchar](50) NOT NULL,
	[color_id] [int] NOT NULL,
 CONSTRAINT [PK_Theme_colors] PRIMARY KEY CLUSTERED 
(
	[element] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Theme_element] UNIQUE NONCLUSTERED 
(
	[element] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Themes]    Script Date: 10/18/2025 3:30:31 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Themes](
	[id] [int] NOT NULL,
	[name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Themes] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Themes_id] UNIQUE NONCLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Themes_name] UNIQUE NONCLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_File_Aliases_alias]    Script Date: 10/18/2025 3:30:31 PM ******/
CREATE NONCLUSTERED INDEX [IX_File_Aliases_alias] ON [dbo].[File_Aliases]
(
	[alias] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Folder_Aliases_alias]    Script Date: 10/18/2025 3:30:31 PM ******/
CREATE NONCLUSTERED INDEX [IX_Folder_Aliases_alias] ON [dbo].[Folder_Aliases]
(
	[alias] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Files]  WITH CHECK ADD  CONSTRAINT [FK_Files_File_Aliases] FOREIGN KEY([name])
REFERENCES [dbo].[File_Aliases] ([alias])
GO
ALTER TABLE [dbo].[Files] CHECK CONSTRAINT [FK_Files_File_Aliases]
GO
ALTER TABLE [dbo].[Folders]  WITH CHECK ADD  CONSTRAINT [FK_Folders_Folder_Aliases] FOREIGN KEY([name])
REFERENCES [dbo].[Folder_Aliases] ([alias])
GO
ALTER TABLE [dbo].[Folders] CHECK CONSTRAINT [FK_Folders_Folder_Aliases]
GO
ALTER TABLE [dbo].[Theme_colors]  WITH CHECK ADD  CONSTRAINT [FK_Theme_colors_Colors] FOREIGN KEY([color_id])
REFERENCES [dbo].[Colors] ([id])
GO
ALTER TABLE [dbo].[Theme_colors] CHECK CONSTRAINT [FK_Theme_colors_Colors]
GO
ALTER TABLE [dbo].[Theme_colors]  WITH CHECK ADD  CONSTRAINT [FK_Theme_colors_Themes] FOREIGN KEY([id])
REFERENCES [dbo].[Themes] ([id])
GO
ALTER TABLE [dbo].[Theme_colors] CHECK CONSTRAINT [FK_Theme_colors_Themes]
GO
USE [master]
GO
ALTER DATABASE [NLS] SET  READ_WRITE 
GO
