name: Build and Release (CMake Multi-Platform)

on:
  push:
    # Запускать workflow только при пуше тега (любой тег)
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: "Manual version override (optional)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  windows-build:
    name: Windows (MSYS2 UCRT64 → NSIS .exe)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-clang
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-nsis

      - name: Read version from VERSION
        shell: msys2 {0}
        run: |
          echo "VERSION=$(tr -d '\r\n' < VERSION)" >> $GITHUB_ENV
          echo "Using VERSION=$VERSION"

      - name: Configure & Build
        shell: msys2 {0}
        run: |
          cmake --preset msys-clang
          cmake --build --preset msys-clang-release

      - name: Package (NSIS .exe)
        shell: msys2 {0}
        run: |
          cpack -G NSIS --config build/msys-clang/CPackConfig.cmake
          ls -la _CPack_Packages/win64/NSIS || true

      - name: Upload Windows installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows_installer
          path: ${{ github.workspace }}/_CPack_Packages/win64/NSIS/nicels-${{ env.VERSION }}-win64.exe
          if-no-files-found: error

  linux-deb:
    name: Ubuntu 24.04 (→ .deb)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Read version from VERSION
        run: |
          echo "VERSION=$(tr -d '\n' < VERSION)" >> $GITHUB_ENV
          echo "Using VERSION=$VERSION"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang pkg-config libssl-dev dpkg-dev

      - name: Configure & Build
        run: |
          cmake --preset linux-clang
          cmake --build --preset linux-clang-release

      - name: Package (.deb)
        run: |
          cpack -G DEB --config build/linux-clang/CPackConfig.cmake
          ls -la _CPack_Packages/Linux/DEB || true

      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debian_package
          path: ${{ github.workspace }}/_CPack_Packages/Linux/DEB/nicels-${{ env.VERSION }}-Linux.deb
          if-no-files-found: error

  linux-rpm:
    name: CentOS Stream 9 (→ .rpm)
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
      # Checkout требует git в контейнере
      - name: Install git (for checkout)
        run: dnf install -y -q git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Read version from VERSION
        run: |
          echo "VERSION=$(tr -d '\n' < VERSION)" >> $GITHUB_ENV
          echo "Using VERSION=$VERSION"

      # --- FIX for "No match for argument: ninja-build" ---
      # В RHEL/Rocky 9 ninja часто в репозитории CRB или EPEL.
      # Включаем CRB, пробуем ninja-build, если не найден — ставим через pip как fallback.
      - name: Enable CRB/EPEL and install build deps
        run: |
          set -e
          dnf -y -q install dnf-plugins-core
          dnf -y -q config-manager --set-enabled crb || true
          dnf -y -q install epel-release || true
          dnf -y -q makecache
          # Основные зависимости
          dnf -y install cmake clang llvm lld pkgconf-pkg-config openssl-devel rpm-build
          # Ninja из реп (CRB/EPEL)
          if ! dnf -y install ninja-build; then
            echo "ninja-build not found in repos, installing via pip..."
            dnf -y install python3-pip
            pip3 install --upgrade pip
            pip3 install ninja
            ln -sf /usr/local/bin/ninja /usr/bin/ninja || true
          fi
          echo "cmake: $(cmake --version | head -1)"
          echo "ninja: $(ninja --version || true)"

      - name: Configure & Build
        run: |
          cmake --preset linux-clang
          cmake --build --preset linux-clang-release

      - name: Package (.rpm)
        run: |
          cpack -G RPM --config build/linux-clang/CPackConfig.cmake
          ls -la _CPack_Packages/Linux/RPM || true

      - name: Upload RPM package artifact
        uses: actions/upload-artifact@v4
        with:
          name: RPM_package
          path: ${{ github.workspace }}/_CPack_Packages/Linux/RPM/nicels-${{ env.VERSION }}-Linux.rpm
          if-no-files-found: error

  release:
    name: Create GitHub Release & Upload Assets
    needs: [windows-build, linux-deb, linux-rpm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for VERSION)
        uses: actions/checkout@v4

      - name: Read version from VERSION
        run: |
          echo "VERSION=$(tr -d '\n' < VERSION)" >> $GITHUB_ENV
          echo "Using VERSION=$VERSION"

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows_installer
          path: artifacts/windows

      - name: Download Debian artifact
        uses: actions/download-artifact@v4
        with:
          name: Debian_package
          path: artifacts/deb

      - name: Download RPM artifact
        uses: actions/download-artifact@v4
        with:
          name: RPM_package
          path: artifacts/rpm

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: nicels ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Windows Installer (.exe)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows/nicels-${{ env.VERSION }}-win64.exe
          asset_name: nicels-${{ env.VERSION }}-win64.exe
          asset_content_type: application/octet-stream

      - name: Upload Debian Package (.deb)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/deb/nicels-${{ env.VERSION }}-Linux.deb
          asset_name: nicels-${{ env.VERSION }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload RPM Package (.rpm)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/rpm/nicels-${{ env.VERSION }}-Linux.rpm
          asset_name: nicels-${{ env.VERSION }}-Linux.rpm
          asset_content_type: application/x-rpm
