name: Build and Release (CMake Multi-Platform)

on:
  push:
    # Запускать workflow только при пуше тега (любой тег)
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: "Manual version override (optional)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  windows-build:
    name: Windows (MSYS2 UCRT64 → NSIS .exe)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-clang
            mingw-w64-ucrt-x86_64-ninja
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-nsis

      - name: Read version from VERSION
        shell: msys2 {0}
        run: |
          echo "VERSION=$(tr -d '\r\n' < VERSION)" >> $GITHUB_ENV
          echo "Using VERSION=$VERSION"

      - name: Configure & Build
        shell: msys2 {0}
        run: |
          cmake --preset msys-clang
          cmake --build --preset msys-clang-release

      - name: Package (NSIS .exe)
        shell: msys2 {0}
        run: |
          cpack -G NSIS --config build/msys-clang/CPackConfig.cmake
          ls -la _CPack_Packages/win64/NSIS || true

      - name: Upload Windows installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows_installer
          path: ${{ github.workspace }}/_CPack_Packages/x86_64/NSIS/nicels-${{ env.VERSION }}-x86_64.exe
          if-no-files-found: error

  linux-deb:
    name: Ubuntu 24.04 (→ .deb)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Read version from VERSION
        run: |
          echo "VERSION=$(tr -d '\n' < VERSION)" >> $GITHUB_ENV
          echo "Using VERSION=$VERSION"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang pkg-config libssl-dev dpkg-dev

      - name: Configure & Build
        run: |
          cmake --preset linux-clang
          cmake --build --preset linux-clang-release

      - name: Package (.deb)
        run: |
          cpack -G DEB --config build/linux-clang/CPackConfig.cmake
          ls -la _CPack_Packages/Linux/DEB || true

      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: Debian_package
          path: ${{ github.workspace }}/_CPack_Packages/x86_64/DEB/nicels-${{ env.VERSION }}-x86_64.deb
          if-no-files-found: error

  linux-rpm:
    name: CentOS Stream 10 (→ .rpm, CMake ≥ 3.28)
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream10
    steps:
      # Контейнер запускается под root, sudo отсутствует — НЕ используем sudo.
      - name: Prepare package manager & git (no sudo)
        shell: bash
        run: |
          set -e
          if command -v dnf5 >/dev/null 2>&1; then
            DNF=dnf5
          elif command -v dnf >/dev/null 2>&1; then
            DNF=dnf
          else
            DNF=microdnf
          fi
          echo "DNF=$DNF" >> $GITHUB_ENV
          $DNF -y -q install git || $DNF -y install git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Read version from VERSION
        shell: bash
        run: |
          echo "VERSION=$(tr -d '\n' < VERSION)" >> $GITHUB_ENV
          echo "Using VERSION=$VERSION"

      - name: Install build dependencies (no sudo)
        shell: bash
        run: |
          set -e
          DNF=${DNF:-dnf5}
          # Основные инструменты
          $DNF -y -q install cmake clang llvm lld pkgconf-pkg-config openssl-devel rpm-build python3-pip || \
          $DNF -y install cmake clang llvm lld pkgconf-pkg-config openssl-devel rpm-build python3-pip
          # Ninja из репозитория; если нет — ставим через pip
          $DNF -y -q install ninja-build || $DNF -y install ninja-build || {
            pip3 install --upgrade pip
            pip3 install ninja
            ln -sf /usr/local/bin/ninja /usr/bin/ninja || true
          }
          # Гарантируем CMake >= 3.28 (если в репозитории версия ниже — ставим из pip)
          CMAKE_VER=$(cmake --version 2>/dev/null | head -1 | awk '{print $3}')
          MAJOR=${CMAKE_VER%%.*}; REST=${CMAKE_VER#*.}; MINOR=${REST%%.*}
          if [ -z "$CMAKE_VER" ] || [ "$MAJOR" -lt 3 ] || { [ "$MAJOR" -eq 3 ] && [ "$MINOR" -lt 28 ]; }; then
            echo "Installing newer CMake via pip..."
            pip3 install cmake
            hash -r
          fi
          echo "cmake: $(cmake --version | head -1)"
          echo "ninja: $(ninja --version || true)"
          echo "clang: $(clang --version | head -1 || true)"

      - name: Configure & Build
        shell: bash
        run: |
          cmake --preset linux-clang
          cmake --build --preset linux-clang-release

      - name: Package (.rpm)
        shell: bash
        run: |
          cpack -G RPM --config build/linux-clang/CPackConfig.cmake
          ls -la _CPack_Packages/Linux/RPM || true
          ls -la _CPack_Packages/Linux/RPM/RPMS || true

      - name: Upload RPM package artifact
        uses: actions/upload-artifact@v4
        with:
          name: RPM_package
          path: ${{ github.workspace }}/_CPack_Packages/x86_64/RPM/RPMS/nicels-${{ env.VERSION }}-x86_64.rpm
          if-no-files-found: error

  release:
    name: Create GitHub Release & Upload Assets
    needs: [windows-build, linux-deb, linux-rpm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for VERSION)
        uses: actions/checkout@v4

      - name: Read version from VERSION
        run: |
          echo "VERSION=$(tr -d '\n' < VERSION)" >> $GITHUB_ENV
          echo "Using VERSION=$VERSION"

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows_installer
          path: artifacts/windows

      - name: Download Debian artifact
        uses: actions/download-artifact@v4
        with:
          name: Debian_package
          path: artifacts/deb

      - name: Download RPM artifact
        uses: actions/download-artifact@v4
        with:
          name: RPM_package
          path: artifacts/rpm

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: nicels ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Windows Installer (.exe)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows/nicels-${{ env.VERSION }}-x86_64.exe
          asset_name: nicels-${{ env.VERSION }}-x86_64.exe
          asset_content_type: application/octet-stream

      - name: Upload Debian Package (.deb)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/deb/nicels-${{ env.VERSION }}-x86_64.deb
          asset_name: nicels-${{ env.VERSION }}-x86_64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload RPM Package (.rpm)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/rpm/nicels-${{ env.VERSION }}-x86_64.rpm
          asset_name: nicels-${{ env.VERSION }}-x86_64.rpm
          asset_content_type: application/x-rpm
